resources:
  - manifests/statefulset.yaml
  - manifests/service.yaml
  - manifests/ingress.yaml
  - manifests/external-secrets.yaml
  - manifests/slack-bot-clusterrole.yaml
  - manifests/slack-bot-clusterrolebinding.yaml
  - manifests/slack-bot-serviceaccount.yaml
#  - manifests/external-config.yaml


configMapGenerator:
  - name: selfdiagnose
    files:
      - selfdiagnose.py=selfdiagnose.py
  - name: count-tokens
    files:
      - count_tokens.py=count_tokens.py
  - name: slack-bot
    files:
      - main.py=main.py
  - name: run-command
    files:
      - run-command.py=run-command.py
  - name: argocd-auth
    files:
      - argocd_auth.py=argocd_auth.py
  - name: git-config
    files:
      - git_config.py=git_config.py
  - name: slack
    files:
      - slack.py=slack.py
  - name: elastic
    files:
      - elastic.py=elastic.py
  - name: chatgpt
    files:
      - chatgpt.py=chatgpt.py
  - name: external-config
    envs:
      - manifests/external-config.yaml