ES_URL=https://elasticsearch-master.logging.svc:9200
es_index=reaction
es_ca_certs=/app/ca.crt
ES_EXT_URL=https://es.opencd.opsmx.org

slack_auth_url=https://slack.com/api/auth.test
slack_post_url=https://slack.com/api/chat.postMessage

max_response_tokens=500
temperature=0.0
top_p=0.5
model=gpt-4o
AUTO_RUN=false
GIT_USER_EMAIL=gopaljayanti@opsmx.io
GIT_USER_NAME=gopaljaynthi

SAVE_TOKEN_USE_SUMMARY=true
MAX_USER_INPUT_TOKENS=6000
LOG_LEVEL=INFO
STORAGE_BACKENDS=file_storage
FS_INDEX=/argonaut/file_storage