apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: slack-bot
spec:
  serviceName: slack-bot
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: slack-bot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: slack-bot
    spec:
      serviceAccount: slack-bot
      serviceAccountName: slack-bot
      containers:
        - name: main
          image: gopalvithaljayanthi/slack-bot:v7
          imagePullPolicy: Always
          command: ["python"]
          args: ["/app/main.py"]
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-token
                  key: GITHUB_TOKEN
            - name: ES_PWD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-master-credentials
                  key: password
            - name: ES_USER
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-master-credentials
                  key: username
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-bot-token
                  key: SLACK_BOT_TOKEN
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: open-api-key
                  key: OPENAI_API_KEY
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: slack-signing-secret
                  key: SLACK_SIGNING_SECRET
          envFrom:
            - secretRef:
                name: argocd-for-slack
            - configMapRef:
                name: external-config
          volumeMounts:
            - name: git-auth
              mountPath: "/app/git_config.py"
              subPath: "git_config.py"
            - name: slack-bot-script
              mountPath: "/app/main.py"
              subPath: "main.py"
            - name: es-ca-crt
              mountPath: "/app/ca.crt"
              subPath: "ca.crt"
            - name: kubeconfigs
              mountPath: "/root/.kube/"
            - name: argonaut-data
              mountPath: "/argonaut"
      volumes:
        - name: git-auth
          configMap:
            name: git-config
        - name: argocd-auth
          configMap:
            name: argocd-auth
        - name: slack-bot-script
          configMap:
            name: slack-bot
        - name: es-ca-crt
          secret:
            secretName: elasticsearch-master-certs
        - name: kubeconfigs
          secret:
            secretName: kubeconfigs
  volumeClaimTemplates:
    - metadata:
        name: argonaut-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 6Gi
