name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check for Docker credentials
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ] || [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "Docker credentials are not set."
            exit 1
          else
            echo "Docker credentials are set."
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract repository name and date
        id: vars
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ env.DATE }}-${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:latest

      - name: Print image digests
        run: |
          echo "Digest for latest tag: ${{ steps.docker_build.outputs.digest }}"
          echo "Digest for commit ID tag: ${{ steps.docker_build.outputs.digest }}"
      - name: Verify image existence on Docker Hub
        run: |
          token=$(curl -s -X POST https://hub.docker.com/v2/users/login/ -d '{"username": "${{ secrets.DOCKER_USERNAME }}", "password": "${{ secrets.DOCKER_PASSWORD }}"}' -H "Content-Type: application/json" | jq -r .token)
          response=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: JWT $token" https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}/tags/${{ env.DATE }}-${{ github.sha }})
          if [ "$response" -eq 200 ]; then
            echo "Image with tag ${{ env.DATE }}-${{ github.sha }} exists in the repository."
          else
            echo "Image with tag ${{ env.DATE }}-${{ github.sha }} does not exist in the repository."
          fi
